#!/usr/bin/env bash
CLEAR='\033[0m'
GREEN='\033[0;32m'
ID='[a-zA-Z_0-9]+-[0-9]+'
if ! grep -E "^(Merge|$ID) .+" $1 > /dev/null; then
    id=$( git rev-parse --abbrev-ref HEAD | grep -o -E "$ID" | tr '[:lower:]' '[:upper:]')
    if [ -z "$id" ]; then
        exit 0
    fi
    echo -e Updating commit message to ${GREEN}\""[$id]" `head -n 1 $1`\"${CLEAR}
    echo -n "[$id] " | cat - $1 > /tmp/out && mv /tmp/out $1
fi
